name: Merchant
main: me.raptor.main.Main
version: 0.1
author: RAPTOR
description: No Desc
api-version: 1.16
depend: [LibsDisguises, MythicMobs, ProtocolLib, AlonsoLevels, PlaceholderAPI, NBTAPI]

commands:
  merchant:
  lvm:
  attrupdate: